name: "publish"
on:
  push:
    branches:
      - main

jobs:
  publish_1:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: publish
    steps:
    - uses: actions/checkout@v2
    - name: rover publish
      uses: ./
      with:
        graph: rover-actions
        variant: current
        federated: true
        subgraph: products
        path: ./test/products.graphql
      env:
        APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
  introspect:
    runs-on: ubuntu-latest
    services:
      apollo:
        image: danielsinclair/apollo-example
    steps:
    - name: rover introspect
      id: introspect
      uses: danielsinclair/rover-introspect-action@v1
      with:
        federated: true
        subgraph: products
        server: http://apollo:3000/
      env:
        APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
  publish_2:
    needs: introspect
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rover publish
      uses: ./
      with:
        graph: rover-actions
        variant: current
        federated: true
        subgraph: products
        artifact: products.graphql
      env:
        APOLLO_KEY: ${{ secrets.APOLLO_KEY }}