name: "publish"
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rover publish
      uses: ./
      with:
        graph: rover-actions
        variant: current
        federated: true
        subgraph: products
        schema: ./test/products.graphql
      env:
        APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
  introspect:
    runs-on: ubuntu-latest
    services:
      apollo:
        image: danielsinclair/apollo-example
    steps:
    - uses: actions/checkout@v2
      with:
        path: publish
    - name: rover introspect
      id: introspect
      uses: danielsinclair/rover-introspect-action@v1
      with:
        federated: true
        subgraph: products
        server: http://apollo:3000/
      env:
        APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
    - run: cat ../products.graphql
    - name: rover publish
      id: publish
      uses: ./publish/
      with:
        graph: rover-actions
        variant: current
        federated: true
        subgraph: products
        schema: ${{ steps.introspect.outputs.path }}
      env:
        APOLLO_KEY: ${{ secrets.APOLLO_KEY }}